"""03_add_info_to_url_model

Revision ID: 167134e822db
Revises: 8e1318d269cc
Create Date: 2023-10-30 22:11:06.805198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167134e822db'
down_revision: Union[str, None] = '8e1318d269cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_urls', sa.Column('total_clicks', sa.Integer(), nullable=False))
    op.add_column('short_urls', sa.Column('full_info', sa.JSON(), nullable=True))
    op.drop_column('short_urls', 'clicks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_urls', sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('short_urls', 'full_info')
    op.drop_column('short_urls', 'total_clicks')
    # ### end Alembic commands ###
