"""04_unique_field

Revision ID: 1d337c8fd50c
Revises: 167134e822db
Create Date: 2023-11-01 10:08:55.814270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d337c8fd50c'
down_revision: Union[str, None] = '167134e822db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'short_urls', ['shorten_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'short_urls', type_='unique')
    # ### end Alembic commands ###
