"""02_changing_model-db

Revision ID: 8e1318d269cc
Revises: 958144085873
Create Date: 2023-10-29 19:18:05.218902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1318d269cc'
down_revision: Union[str, None] = '958144085873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_urls', sa.Column('shorten_url', sa.String(), nullable=False))
    op.add_column('short_urls', sa.Column('password_for_deleting', sa.String(), nullable=False))
    op.drop_column('short_urls', 'shorten_url_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_urls', sa.Column('shorten_url_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('short_urls', 'password_for_deleting')
    op.drop_column('short_urls', 'shorten_url')
    # ### end Alembic commands ###
